### PR TITLE
Setup.hs: Updates for ghc-8.2 and Cabal 2.0

### PR DESCRIPTION
**Pull request by erikd-ambiata**
Tested with GHC 7.10, 8.0 and 8.2.
    
Because this script is run with `runhaskell` it is not possible
to use the normal cabal `MIN_VERSION_<pkg>` macros and have to
rely on GHC version information instead.

! @charleso @jystic @nhibberd 
/jury approved @charleso

### CODE REVIEW

**Comment by charleso** [comment]
👍 

Would want to check with Jacob/Nick too

**Comment by erikd-ambiata** [comment]
Problem is actually more subtle than this PR suggests. Needs more work.

**Comment by erikd-ambiata** [comment]
Fixed now. I've also put this version to work in parsley. See  https://github.com/ambiata/parsley/pull/37

Won't merge this until all three of you give it 👍 .

File: src/Setup.hs [hunk 1]
```diff
@@ -4,17 +4,29 @@ import           Data.Char (isDigit, toLower)
...
+import           Distribution.Version (Version, showVersion, versionNumbers)
+import           Distribution.Simple.BuildPaths (autogenModulesDir)
+
+-- This version of Setup.hs only builds against version 2.0 of the Cabal
+-- library, but can be built with the cabal-install version 1.24 as long
+-- as the cabal file includes:
+--
+--    custom-setup
+--        setup-depends:       base
+--                           , Cabal >= 2.0
```
Comment (jystic) [inline src/Setup.hs]: how does mafia cope with the `custom-setup` section? I know it's caused some problems in the past is all

Comment (erikd-ambiata) [reply src/Setup.hs]: It copes as long as cabal-install is 1.24 or later. Previous problems were probably cabal-install 1.22 which I have confirmed not to work.

**Comment by jystic** [comment]
> Because this script is run with `runhaskell` it is not possible to use the normal cabal `MIN_VERSION_<pkg>` macros and have to rely on GHC version information instead.

Is this the case with GHC 8? I thought that GHC itself generates these macros from v8 onwards

**Comment by erikd-ambiata** [comment]
> Is this the case with GHC 8? I thought that GHC itself generates these macros from v8 onwards

Maybe. Main things is that we want to build with any combination of ghc 7.10/8.0 and cabal-install 1.24/2.0.

**Comment by erikd-ambiata** [comment]
This still doesn't work in all situations. Trying to figure out why.

**Comment by erikd-ambiata** [comment]
The version in commit 0292d0e10f1fe830f5e6e9692587a873af19355c is the same as the one that is currently in Walrus.

**Comment by charleso** [comment]
@erikd-ambiata I'm having problems using this locally:

```
> mafia build
Failed to run 'cabal sdist' for source package: ../walrus-conduit
Process failed with exit code: 1
[1 of 1] Compiling Main             ( dist/setup/setup.hs, dist/setup/Main.o )
dist/setup/setup.hs:1:2: error: parse error on input ‘#!/’
```

```
> ghc --version
The Glorious Glasgow Haskell Compilation System, version 8.0.1
> cabal --version
cabal-install version 1.24.0.1
compiled using version 1.24.1.0 of the Cabal library
```

If I take out the first line of the `Setup.hs` file it work (eg. take out the shebang).

**Comment by erikd-ambiata** [comment]
That's weird, because that file works in Walrus. 

I do notice that in Walrus the file has execute permissions:
```
> ls framework/Setup.hs 
-rwxr-x--- 1 erikd erikd 5188 Jan  3 14:33 framework/Setup.hs
```
What about yours?

**Comment by charleso** [comment]
https://github.com/haskell/haskell-ide-engine/issues/333

**Comment by charleso** [comment]
(It's an OSX thing apparently)

**Comment by erikd-ambiata** [comment]
Actual issue is the GHC on OSX uses Clang as the C pre-processor whereas on Linux GCC will be used.
